# Generated by Django 4.2.2 on 2023-06-29 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_comments_feedback_is_interesting'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='display_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
